name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build-push:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [ '16-user', '16-alpine3.14-user' ]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./.github/docker/
          file: ./.github/docker/${{ matrix.tag }}.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/node:${{ matrix.tag }}
